tajutaiou <- read.csv("sample3.csv",head=TRUE)
watashi <- factor(tajutaiou$私, level = c(0:1),labels = c("F","T"))
kazoku <- factor(tajutaiou$家族, level = c(0:1),labels = c("T","F"))
shussan <- factor(tajutaiou$出産, level = c(0:1),labels = c("F","T"))
kodomo <- factor(tajutaiou$子供, level = c(0:1),labels = c("F","T"))
okane <- factor(tajutaiou$お金, level = c(0:1),labels = c("F","T"))
kenko <- factor(tajutaiou$健康, level = c(0:1),labels = c("F","T"))
time <- factor(tajutaiou$time, level = c(0:3),labels = c("asa","hiru","yu","yoru"))
tajutaiou2 <- data.frame(watashi,kazoku,shussan,kodomo,okane,kenko,time)
summary(tajutaiou2)
library(MASS)
result <- mca(tajutaiou2)